language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: Q44u14IX5MruSU23EXb3RcEE8/11H5EbAgGcVSvNsEgJJd5aqWxhUwcNJKbn2XLbEdG85sNsF0R1OREP8/oqALM2+dwsSZXxa3/0XFj72nKAxs0MZrm6gS5lLCIKbAoEzvF83c8w12xL33jPXTBzyhbWgBXk14NKidnq9Qlpcxeazfg6pZhjnd2McGpDQy4Wszrql85MKC7aabL6y9YxYyHduo4pfL1TtMouC0Ilo/jLQ+c2sxuCkeCPRvNKSThmewVfz8H37siiuVOms4aBPURN/gyaSvKlVMCVOvSdwQRN9SgOkqy7/E/JqR9KjypwrNHrRyu7HZfkUpR94z8nrsR3LJSFxrCG8Pix+Q37Cuxn+cWdDJTODSFDs4Jfmz+jS/gGDYeiGiSkWC6Q6tMtu3UMYzU3smvGXRYuMgVB0zGqVk38dr4o7DA75WfYYaBOa20s5ZSkWqcDtJ5PPYhuRCCv/qYHK9ta9kMWBYLhDR6H/3yOAUdIm/QqIAct6f6eQDXSE3GRCOoFf7NezgyNtmRhlVMZX74Xa6WW5PIWqjRQpZRLqc6dGFzhmua3JNC/C55dGCQKi6JdUrfFO0FZzNzFCPjhMQcT/6tObDC0BFCVT9wbXrn2TWiloS5PO18vOZeMf7rzJ55vveWRZg9rBkk//D65vct5syQMqfxaGwU=
  - secure: cSb2841rnFH7VQc1Z4QwUktwVo2s5txiOO/ZZSJMozgtYgBvyPe5LWFwKGMNME0jiu59O8calzJmpgkpbyfR1yFfbAVmfFVna2Q8f5J9uFjAhwJlF6F9UQQnHJdwQnpP2G+rzWTReBhQaYxUofT4jedW71ib6dYXMFDVRm7sz+bUpZ0UtGMvkvKtrN4/JUKrX+O8er8nBvrTnBwRI0rJUuudIXorke6goJJhiI7R4XIrcGAdB565ylIo4IQEtkyruVDnw9ywIPR45L4OC9dpBSIgFPFTQOSPm18gNokapNLdXxJoppu/K4Q6Xj9nmJyF8WcJdkO+5QpSQ0Kkt1caSKxeBoC0dTnk8e59Z9UP4TvK1v/GVZQW/CzsT5/cx+U65zaRQSyOojhpd7klJ+OxC+dbbgMB26sg/LX4+egQTDz6XVuAouACXNQmvTVLtfU/OlkjINXvdSOU+vhUeqBgkvJVZfDBYEabhr6ooy8rZWWLfN/PZ8c4LpLP3pm9gJqv95e9BWLzcHrXoiS/WYMlcF5NSFRqiJYk6XicVKa+SgVQwHa2+k31FsVBMR+0qF1p6Kbrne/LlnXYBKjt07mmjmo9xc0deNnb5mgliOwmdciNNUvKr/2iBomcdtbal67eD07oDfVTj1UqzgkyxXvGPjM8KT5Cn+LvP+bxv3+4THk=
dist: trusty